compile :
	ls *.cpp | while read f | do g++ -c $f; done;
	
#AlchemyFlashMain.o : AlchemyFlashContext3D.h
#AlchemyFlashContext3D.o : AlchemyFlashContext3D.h

.PHONY : clean
clean :
	-rm ls *.o|while read f;